
name: Staging workflow

on:
  push:
    branches: [ staging ]
#   pull_request:
#     branches: [ staging ]

jobs:
  build:

    strategy:
      matrix:
        node_version: [12.x]
        python_version: [3.8.x]

    runs-on: ubuntu-latest

    steps:

    - name: Install AWS CLI
      run: sudo apt-get install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws-region: us-east-1

    - name: Branch Name
      run: echo Running on branch ${GITHUB_REF##*/}
        
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install NPM Packages
      run: |
        sudo npm install -g aws-cdk
        cdk --version

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    
    - name: Install Python Dependencies & Deploy Stacks
      run: |
        python -m pip install --upgrade pip

        python3 -m venv .env
        source .env/bin/activate
        pip3 install -r requirements.txt

        cdk synth cdk-lambda
        cdk synth cdk-api
        cdk synth cdk-memcached

        cdk deploy cdk-lambda -v

# cdk bootstrap aws://065035205697/us-east-1